# COMMON SETTINGS FOR APP SERVICES
x-app-common: &app-common
  networks:
    - my-bridge-network
  env_file:
    - .env
  environment:
    PGUSER: ${PGUSER}
    PGPASSWORD: ${PGPASSWORD}
    PGPORT: ${PGPORT}
    PGDATABASE: ${PGDATABASE}
    PGHOST: ${PGHOST}


services:
  project-db:
    <<: *app-common
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"  # SHOULD NOT BE USED IN PROD ENVIRONMENT!!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 20s
      retries: 5
    volumes:
      - project-db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  project-app:
    <<: *app-common
    image: notexists/job-application-system-app:1.1
    depends_on:
      project-db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs:rw

  project-backup-app:
    <<: *app-common
    image: notexists/db-backup-app:1.1
    depends_on:
      project-db:
        condition: service_healthy
      project-app:
        condition: service_completed_successfully
    volumes:
      - ./logs:/app/logs:rw
      - ./backups:/app/backups:rw

volumes:
  project-db-data:
    driver: local

networks:
  my-bridge-network:
    driver: bridge
    external: true