services:

  custom-airflow:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:latest-python3.11}
    build:
      context: .
      dockerfile: airflow.Dockerfile

  airflow-postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    volumes:
      - airflow-postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - ./dags:/usr/local/airflow/dags

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    command: scheduler
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - ./dags:/usr/local/airflow/dags

volumes:
  airflow-postgres-db-volume: